version: "3.7"
services:
  daily_reminder_birthday:
    container_name: daily_reminder_birthday
    build:
      context: /web/reminder/birthday/daily_reminder
      dockerfile: /web/reminder/birthday/daily_reminder/Dockerfile
    volumes:
      - "/web/reminder/birthday/daily_reminder:/web/daily_reminder"
    restart: always
    command:
        - sh
        - -c
        - |
            ls -lh
            python main.py