# 公众号配置
wechat:
  # 公众号appId  old -> wxd3ede162f10e7dad
  app_id: "wxd4b61a7f83c58271"
  # 公众号appSecret  old -> 5af4879eea3b7f8970b59abacd9600ff
  app_secret: "df0a34b90c2f06ecd9bf3aee6832e4e3"
  # 模板消息id  old -> wgndkmcfa_zH6Q_g1u2-dXg019whLJ1179yUFJYgMl4
  template_id: "j5YLs_KsZkCXdz2eXqwmUnhx_LRABRCrcsXAFgJYEfM"
  # 接收公众号消息的微信号，如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"] old -> ["odSy55tEuY4I8oy5og7ZXtqLrH9s","odSy55i-_7hpDh9JkhW_efpagcZo"]
  user: ["o6VQz54mRfcBogKCgJut2djuOFUs","o6VQz529ZGB8_vEiiVONHRHLUfaI"]
# 信息配置
weather:
  # 和风天气apikey
  weather_key: "9144e221cc214439a06fae9d18cf61e0"
  # 所在地区，可为省，城市，区，县，同时支持国外城市，例如伦敦
  region: "成都"
birthday:
  # 生日1，修改名字为对应需要显示的名字，如果生日为农历，在最前面加上r即可
  she_birthday: {"name": "小糜", "birthday": "r1997-09-08"}
  # 生日2
  my_birthday: {"name": "小刘", "birthday": "r1996-11-14"}
  # 在一起的日子，格式同上，暂不不支持农历
  love_date: "2022-06-22"
# 星座
star:
  she_star: ""